#!/bin/bash

LOG_FILE="/var/log/xklb.log"
LOG_LEVEL="-vv"
XKLB_EXECUTABLE="${XKLB_EXECUTABLE:-lb}"
TMP_DOWNLOADS_DIR="/library/downloads/calibre-web"
SURVEY_DB_FILE="${TMP_DOWNLOADS_DIR}/survey.db"
URL="$1"

# Or download largest possible HD-style / UltraHD videos, to try to force
# out-of-memory "502 Bad Gateway" for testing of issues like #37 and #79
# FORMAT_OPTIONS="--format-sort size"

FORMAT_OPTIONS="--format best --format-sort 'tbr~1000'"
XKLB_FULL_CMD="${XKLB_EXECUTABLE} tubeadd ${SURVEY_DB_FILE} ${URL} ${LOG_LEVEL} && ${XKLB_EXECUTABLE} dl ${SURVEY_DB_FILE} --prefix ${TMP_DOWNLOADS_DIR} --write-thumbnail ${FORMAT_OPTIONS} --video ${URL} ${LOG_LEVEL}"

mkdir -p ${TMP_DOWNLOADS_DIR}

# Function to log messages with different levels
log() {
    local level=$1
    local message=$2
    if [[ $message == *"downloading"* ]]; then
        echo "$message"
    else
        echo "$(date +'%Y-%m-%d %H:%M:%S') - [$level] $message" >> ${LOG_FILE}
    fi
}

if ! command -v "${XKLB_EXECUTABLE}"; then
    log "Error" "xklb could not be found. Please install xklb and try again."
    exit 1
fi

if [ $# -eq 0 ]; then
    log "Error" "No arguments provided. Please provide a URL to download."
    exit 1
fi

log "Info" "xklb version: $(${XKLB_EXECUTABLE} --version)"

if mv ${SURVEY_DB_FILE} ${SURVEY_DB_FILE}.$(date +%F_%T_%Z) 2> /dev/null; then
    log "Info" "Old ${SURVEY_DB_FILE} moved aside."
fi

log "Info" "Running command: ${XKLB_FULL_CMD}"

# Run the command in the background and capture the PID
eval "${XKLB_FULL_CMD}" > >(while read -r line; do log "Info" "$line"; done) 2> >(while read -r line; do log "Error" "$line"; done) &
pid=$!

# Wait for the background process to complete
wait $pid

# Check the exit status of the command
if [ $? -eq 0 ]; then
    log "Info" "Download completed successfully."
else
    log "Error" "An error occurred while running the command."
    exit 1
fi
