#!/bin/bash

FILE_PATH="$HOME/.local/pipx/venvs/xklb/lib/python3.12/site-packages/xklb/createdb/tube_add.py"

# Check if the patch flag exists
if ! grep -q "# PATCHED by IIAB: so live_status and error columns can be added" "$FILE_PATH"; then
    echo "Patch to tube_add.py seems missing. Reapplying patch... (helps add columns live_status and error)"
else
    echo "tube_add.py is already patched (helps add columns live_status and error). No changes necessary."
    exit 0
fi

# Logic to add 'live_status' and 'error' columns (needed when xklb-metadata.db is created or REcreated!)
sed -i '/"time_deleted": 0,/a \ \ \ \ \ \ \ \ "live_status": None, \n\ \ \ \ \ \ \ \ "error": None,' "$FILE_PATH"
echo "# PATCHED by IIAB: so live_status and error columns can be added" >> "$FILE_PATH"
echo "tube_add.py has been successfully patched"
