#!/bin/bash

# FILE_PATH="$HOME/.local/pipx/venvs/xklb/lib/python3.12/site-packages/xklb/createdb/tube_add.py"
updatedb
FILE_PATH=$(locate /site-packages/xklb/createdb/tube_add.py | grep /pipx/venvs/xklb/lib/ | grep /root/.local/ | head -1)
FLAG_STR="# PATCHED by IIAB: so live_status and error columns can be added"

# Check if the patch flag exists
if ! grep -q "$FLAG_STR" "$FILE_PATH"; then
    echo "Patch to tube_add.py seems missing. Applying patch... (helps add columns live_status and error)"
else
    echo "tube_add.py is already patched (helps add columns live_status and error). No changes necessary."
    exit 0
fi

# Logic to add 'live_status' and 'error' columns (needed when xklb-metadata.db is created or REcreated!)
sed -i '/"time_deleted": 0,/a \ \ \ \ \ \ \ \ "live_status": None, \n\ \ \ \ \ \ \ \ "error": None,' "$FILE_PATH"
echo "$FLAG_STR" >> "$FILE_PATH"
echo "tube_add.py has been successfully patched"
